### ISSUE TITLE
Move date in confirmed payslips where force period used

### ISSUE THREAD

**Issue by JordiBForgeFlow** [OCA/hr#135]
Dear colleagues,

We have noticed that it is not possible to confirm a payslip for a previous period (use the force period field), if the Salary Journal has the option 'Check Date in Period' set. The application defaults the move date to today's date.

But... we don't want to create a payslip journal entry with date 1st september for a payslip that was supposed to be paid on 1st august. The date and the period should match.

IMHO upon confirmation of a payslip the application should fetch the date from 'Date of Payment' in the payslip as the date to post to.

We would create a module that corrects the account move before it is posted, using the date of payment instead of today's date.

Please let me know if you agree with this approach.

**Comment by ghost** [comment]
@jbeficent, See module hr_period. It is still in v7, but it may be ported soon to v8. It does not fix the accounting, but it adds payroll periods management.

There are 3 dates on a payslip, the "Date of Payment", the "Date From" and the "Date To". The date of payment should be used for the payment of the payslip. The payslip's account move is an "Expense move" which theorically should not imply any bank/cash account. The "date from" or the "date to" should be used because this is when your salary expense is engaged.

**Comment by JordiBForgeFlow** [comment]
Thanks @dufresnedavid. I will then use "Date To". Once the module is ready I will submit a PR.

**Comment by ghost** [comment]
@jbeficent Ok, excellent
