### ISSUE TITLE
hr_expense_invoice V.11

### ISSUE THREAD

**Issue by ghost** [OCA/hr#573]
When I try to pay the employee's expense this message appears:
![1](https://user-images.githubusercontent.com/25029267/54755258-df739a00-4be5-11e9-98cd-2b2e3b5ba84b.png)
But I have checked the accounting account and it's not reconcilied.
![2](https://user-images.githubusercontent.com/25029267/54755520-60329600-4be6-11e9-8bed-a546f7fb423a.png)
And when I validated the expense this jounal entry was made. It is correct and the invoice is paid.
![3](https://user-images.githubusercontent.com/25029267/54755374-1ea1eb00-4be6-11e9-9ec0-b362b5f94510.png)
But I can't pay to my employee.

**Comment by kittiu** [comment]
```
diff --git a/addons/hr_expense/wizard/hr_expense_sheet_register_payment.py b/addons/hr_expense/wizard/hr_expense_sheet_register_payment.py
index f77f013d..66d6c116 100644
--- a/addons/hr_expense/wizard/hr_expense_sheet_register_payment.py
+++ b/addons/hr_expense/wizard/hr_expense_sheet_register_payment.py
@@ -106,7 +106,7 @@ class HrExpenseSheetRegisterPaymentWizard(models.TransientModel):
 
         # Reconcile the payment and the expense, i.e. lookup on the payable account move lines
         account_move_lines_to_reconcile = self.env['account.move.line']
-        for line in payment.move_line_ids + expense_sheet.account_move_id.line_ids:
+        for line in payment.move_line_ids + expense_sheet.account_move_id.line_ids.filtered(lambda l: not l.reconciled):
             if line.account_id.internal_type == 'payable':
                 account_move_lines_to_reconcile |= line
         account_move_lines_to_reconcile.reconcile()
```

Hi, I found that, because this module will create 2 payable line for Expense. 1 payable line will already reconcile with invoice and make invoice paid. 1 payable line is left to be reconciled when doing register payment on expense.

But from Odoo core, it is getting both line (1 reconciled and 1 is not) and try to reconcile with payment entry. So, it shows error.

I see that, to fix it, we should only select unreconciled payable `expense_sheet.account_move_id.line_ids.filtered(lambda l: not l.reconciled)`

But this has to do in core Odoo.

**Comment by kittiu** [comment]
Without fixing in core Odoo, I think there are 2 ugly way.
1) Do a hook addon, just to fix this
2) Inherit on move's reconcile() method, and pass some context to ignore the reconciled payable.

What is the better way in OCA eye? @pedrobaeza

**Comment by kittiu** [comment]
No one have this problem when using hr_expense_invoice?
I am curious (may be some setting will solve this?)

**Comment by ghost** [comment]
Is it fixed @kittiu ? I see you have done a Merged.

**Comment by kittiu** [comment]
I change to fix in hr_expense_invoice, because I realize it should be difficult to change in core Odoo.
So, yes, it is fixed. But not in the one merged, we have quite enhancement after that.
https://github.com/OCA/hr/issues/615
https://github.com/OCA/hr/pull/622
So, I choose to fix here,
https://github.com/ecosoft-odoo/hr/blob/12.0-imp-hr_expense_invoice-options_direct_invoice/hr_expense_invoice/models/account_move_line.py

**Comment by ghost** [comment]
Ok.
Thanks for the info.
