### ISSUE TITLE
[12.0][BUG] hr_holidays_public: error when inputting Date of Leave Request is Public Holiday have existed on the other Leave Request

### ISSUE THREAD

**Issue by cuongpk** [OCA/hr#646]
![image](https://user-images.githubusercontent.com/23528443/61784854-ad44a400-ae34-11e9-889d-810057bbc970.png)

Please help me to check this issue.
I think we need to call the function check the overlapping date before `_onchange_leave_dates` called.

**Comment by pedrobaeza** [comment]
Please indicate clear steps to reproduce the problem

**Comment by cuongpk** [comment]
> Please indicate clear steps to reproduce the problem
![image](https://user-images.githubusercontent.com/23528443/61782499-55a43980-ae30-11e9-83b0-edb46aab2143.png)
This is my Public holiday.
![image](https://user-images.githubusercontent.com/23528443/61782516-5b9a1a80-ae30-11e9-9e59-0c2cd7c1d7bd.png)
And I have created a new Leave Request, it's still good this step.
![image](https://user-images.githubusercontent.com/23528443/61784873-ba619300-ae34-11e9-9ac0-b17a78edb9d8.png)
Then, I have tried to create a new Leave Request with the same Public Holiday and I get this error.

**Comment by jarroyomorales** [comment]
Well, by looking at the logs you can clearly see that the problem comes from trying to create an interval from an interval that comes from a `resource.calendar.leave` and another one that comes from a public holiday. This didn't happen in 11.0 because intervals were appended using + instead of | , which is redefined by the `Intervals` class.
By changing https://github.com/OCA/hr/blob/12.0/hr_holidays_public/models/resource_calendar.py#L44
 to an empty resource.calendar.leave (`self.env['resource.calendar.leaves']`) you fix the bug, but you lose the reference to the public holiday and it may have side effects.
On the migration to 12.0 I have seen that @alexey-pelykh and @pedrobaeza talked about assigning a `resource.calendar.leave` to every public holiday, which may be the best solution here.
What do you think?

**Comment by meigallodixital** [comment]
I made a leave (holiday) from July 12 to 31 and 25 as a holiday and I confirm the calculation fails in theoretical too.

Traceback: https://pastebin.com/aYENSuFq

**Comment by pedrobaeza** [comment]
@alexey-pelykh can you please check this?

**Comment by ivantodorovich** [comment]
Following up on the discussion in https://github.com/OCA/hr/pull/534#issuecomment-449573880

If I understand correctly, the idea that hr_holidays_public module will become a manager of `resource.calendar.leaves`, right?

What about making it a manager of `hr.leaves` instead?

There are some beneficts:

**Easier implementation of state/city public holidays**
`hr.leave` model has the `holiday_type` field which already handles `company`, `department` and `category` values (apart from `employee`). When validated, individual `employee` leaves are created.
It would be easy to include a `holiday_type = location` and a few fields like `country_id` and `state_id` (and why not `city_id`)
https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L158
https://github.com/odoo/odoo/blob/12.0/addons/hr_holidays/models/hr_leave.py#L722

**Standard leaves workflow**
In fact, the public holidays manager could just be a few views on `hr.leave` + the utility wizard to generate new public holidays based on the previous year (or possibly retrieve them from an external service).
They can be generated as draft (and probably *should* (*)), and then validated by the HR manager when we get close to that date.

(*): the employee search happens on validation.

**Automatic Integration with project**
module project_timesheet_holidays works at the `hr.leave` model: https://github.com/odoo/odoo/blob/8f4b98e67fe49516c0c830524de351db67c58357/addons/project_timesheet_holidays/models/hr_holidays.py#L46)

**Comment by jarroyomorales** [comment]
Okay, I agree with you that using `hr_leaves` and assigning holidays by location would be a good solution but at this point I think the impact to other modules or people already using it in production would be too big.

I think the only option is to try solving this annoying bug but maintaining the core of the module.

**Comment by ivantodorovich** [comment]
So the idea is.. target it for 13.0? We'll need migration scripts either way.
Personally I need the project integration I mentioned. It's not related directly with this issue but we can solve both things at the same time.

**Comment by jarroyomorales** [comment]
Pffff you are right, but at least you are executing the script when you decide to migrate. If we update it now, how can I install this update without losing everything? Because if I don't update I have to live with this bug...
I don't know which is the best solution. :sweat:

**Comment by pedrobaeza** [comment]
Migration scripts can be done in the middle of a version.

**Comment by jarroyomorales** [comment]
Oh, I didn't know that. In that case I think we should try @ivantodorovich version. Thank you!

**Comment by ivantodorovich** [comment]
There's one thing in particular that I dont like: it's the fact that individual leaves would be created from this new 'location' hr.leave when it's validated. That means that if we update or create a new employee after this public holiday leave is validated, the individual leaves won't be updated.

It's an issue that already exists in odoo with 'department' or 'category' leaves, I think. Only in this case might be more relevant.

I guess it's not that bad, since HR managers can manually handle these cases. And, overall, they will have more visibility on how the public holidays are applied than what the have right now. Everything will be explicit.

@alexey-pelykh what do you think?
we are ok to work on this if agree on conception

**Comment by jarroyomorales** [comment]
@ivantodorovich @alexey-pelykh @pedrobaeza What do we do with this?
