### ISSUE TITLE
Validation Error in hr_public_holidays module v12

### ISSUE THREAD

**Issue by SSanfilippo** [OCA/hr#755]
Hi at all,
I think that the module had same issue that was fixed in v11: https://github.com/OCA/hr/issues/569

Odoo Version - v12 Community

1. Create a new Public Holiday.
2. Add a new Public holiday line.
3. Select the date, add name and untick the Date may change Boolean.

On save get error on Date not filled.

**Comment by jarroyomorales** [comment]
At least for me it is not clear what's the purpose of `variable_date` . I thought it was used to indicate if that holiday is on the same day every year or not. (Christmas is always the 25th of December but Easter changes every year for example, at least in Spain).
If the only purpose of that variable is to set the `date` field as readonly I think we can just get rid of it....

**Comment by SSanfilippo** [comment]
Yes, I confirm that I set a fixed holiday or variable holiday I get always same error.

In Odoo 11 was fixed with a few line of code, I try to reapply the fix (the files are as previous of this fix), but the error remain.

**Comment by jarroyomorales** [comment]
The function in https://github.com/OCA/hr/blob/11.0/hr_holidays_public/models/hr_holidays_public.py#L196 that was made to solve the error sets the date to False and raises a warning. It sets date to False since it has lost the reference to its previous value, which doesnt make any sense, since at the end you are also changing the date and not solving anything.
We should first figure out the meaning of `variable_date` and then do something according to that.

@feketemihai @mtelahun @alexis-via @saltonmassally @yelizariev @bassn @pedrobaeza @alexey-pelykh, you are contributors/authors of this module, any answer to this?

**Comment by kensshiro** [comment]
The problem is caused by an attribute in the file hr_holidays_public_view.xml. Set Date as readonly and in the create or write, the field does not take it by having this attribute. 
This can be fixed by adding the field to the values ​​variable for saving. 
The use of the variable_date field that I would give would be the following:
Add to the wizard the creation of a new Plan, the detection of those records with the field activated for modification with the new dates before the creation of the new Plan. So we can solve Easter, Easter Week, etc. in Spain, since they vary every year. And the variable_date field by default false.

**Comment by jarroyomorales** [comment]
@kensshiro I completely agree with you. In fact I already had an implementation of what you say in the last paragraph, I'm going to create a PR and see what people thinks

**Comment by kensshiro** [comment]
Thanks!! It's good idea!!
