### ISSUE TITLE
hr_expense_sequence is not working for multi_company env

### ISSUE THREAD

**Issue by hitrosol** [OCA/hr#979]
hi @Saran440,

it seems the hr_expense_sequence is not working for multicompany environment. 
I found error message as follow when i try to submit the expense report of the second company. It works well for the first company.

![image](https://user-images.githubusercontent.com/5949936/109611917-8fd3d200-7b61-11eb-8667-e1af8d05f8dc.png)

thanks

**Comment by Saran440** [comment]
@hitrosol Thank you for your reported bug. This month I very busy.
I will fix it as soon as possible or can you fix?

**Comment by Saran440** [comment]
@hitrosol I tested with multi company and found this error.
BUT it error because expense sequence is default first company.

you can check and config following:
1. Open dev mode
2. Go to Settings > Technical > Sequence & Identifiers > Sequences
3. Search name "Expense report sequence". this sequence default first company only.
if you need to common sequence, you can edit company out.
if not, you can create new sequence for second company.
![Selection_001](https://user-images.githubusercontent.com/20896369/117539683-ec59de80-b035-11eb-8d12-af4f078d7886.png)

**Comment by Saran440** [comment]
@hitrosol I tested with multi company and found this error.
BUT it error because expense sequence is default first company.

you can check and config following:
1. Open dev mode
2. Go to Settings > Technical > Sequence & Identifiers > Sequences
3. Search name "Expense report sequence". this sequence default first company only.
if you need to common sequence, you can edit company out.
if not, you can create new sequence for second company.
![Selection_001](https://user-images.githubusercontent.com/20896369/117539683-ec59de80-b035-11eb-8d12-af4f078d7886.png)

**Comment by hitrosol** [comment]
Thanks @Saran440  for the explanation
